project_id = "mpvslenznhslqajgvfqw"

[functions.implantador-chat]
verify_jwt = false

[functions.implantador-prefill]
verify_jwt = false

[functions.compliance-check]
verify_jwt = false

[functions.rag-generate]
verify_jwt = false

[functions.rag-save]
verify_jwt = false
